spring.application.name=StudentManagement

Spring.datasource.url=jdbc:mysql://localhost:3306/StudentManagement
Spring.datasource.username=root
spring.datasource.password=5yncri5e!0119
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true

